// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/atliliw/microg/examples/user/srv/config"
	"github.com/atliliw/microg/examples/user/srv/controller"
	"github.com/atliliw/microg/examples/user/srv/data"
	"github.com/atliliw/microg/examples/user/srv/server"
	"github.com/atliliw/microg/examples/user/srv/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitApp Wire 注入器入口
func InitApp() (*server.App, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	userStore, err := data.NewUserStore(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userService := service.NewUserService(userStore)
	userServer := controller.NewUserServer(userService)
	rpcserverServer := server.NewRPCServer(configConfig, userServer)
	registry := server.NewRegistrar(configConfig)
	app := server.NewApp(configConfig, rpcserverServer, registry)
	serverApp, cleanup, err := server.NewAppWrapper(configConfig, app)
	if err != nil {
		return nil, nil, err
	}
	return serverApp, func() {
		cleanup()
	}, nil
}

// wire.go:

// ProviderSet 依赖提供者集合
var ProviderSet = wire.NewSet(config.ProviderSet, data.ProviderSet, service.ProviderSet, controller.ProviderSet, server.ProviderSet)
