// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"microg/examples/user/client/config"
	"microg/examples/user/client/controller"
	"microg/examples/user/client/data"
	"microg/examples/user/client/server"
	"microg/examples/user/client/service"
)

// Injectors from wire.go:

// InitApp Wire 注入器入口
func InitApp() (*server.App, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	registry := data.NewDiscovery(configConfig)
	userClient := data.NewUserClient(configConfig, registry)
	userRepo := data.NewUserRepo(userClient)
	userService := service.NewUserService(userRepo)
	userController := controller.NewUserController(userService)
	restserverServer := server.NewHTTPServer(configConfig, userController)
	app, cleanup, err := server.NewApp(configConfig, restserverServer)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// ProviderSet 依赖提供者集合
var ProviderSet = wire.NewSet(config.ProviderSet, data.ProviderSet, service.ProviderSet, controller.ProviderSet, server.ProviderSet)
